name: ci

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'

    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: nestesteira:latest
      
      # - name: 'Build Inventory Image'
      #   run: |
      #         docker build . --tag ghcr.io/wevbarrosmoura/nestesteira:latest
      #         docker push ghcr.io/wevbarrosmoura/nestesteira:latest
          

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: 'wevbarrosmoura/nestesteira:latest'
      #     format: 'table'
      #     exit-code: '1'
      #     ignore-unfixed: true
      #     vuln-type: 'os,library'
      #     severity: 'CRITICAL'
      #   continue-on-error: true
